### ISSUE TITLE
Documentation Enhancement Request

### ISSUE THREAD

**Issue by hackdefendr** [jtarrio/radioreceiver#1]
What are the next steps once I have the `dist` folder populated? Do we just copy the `apps` and `tools` folders into a web accessible folder like /var/www/html? I attempted both, but no matter what browser I run it says its not compatible.

```
This browser does not support the HTML5 USB API. Please try Chrome, Edge, or Opera on a computer or Android.
```

I tried Chrome, Edge, and Opera. None of them work.

**Comment by virtadpt** [comment]
You only have to serve the contents of the dist/apps/radioreceiver/ directory to get the whole thing.  However, the error message is telling you what's wrong: Your web browser doesn't support the HTML5 USB API.  I'm guessing you're using Firefox or one of its derivatives because they haven't implemented it yet.

Just out of curiosity, do you have an RTL-SDR plugged into your machine?

**Comment by hackdefendr** [comment]
OK I did most of it right. I see the web page, can click the buttons and most things work. I'm in Chrome, and Opera, and both show the Web USB API error. I guess this has to be done on a PC, not Mac?

**Comment by jtarrio** [comment]
As @virtadpt said, copy the content of dist/apps/radioreceiver to your webroot.

For the other question, my regular development machine is a Mac, so that shouldn't be the problem. I'm wondering why it wouldn't have access to the WebUSB API. Is it your personal computer, or is it owned/managed by a company?

(I'm assuming that my version on https://radio.ea1iti.es/ doesn't work for you, either.)

**Comment by jtarrio** [comment]
Oh, WebUSB only works for pages served through HTTPS, not HTTP.

I'll add documentation about this tomorrow.

**Comment by hackdefendr** [comment]
Yep that was the trick. Doh! I reconfigured Nginx for https and its all happy now.

**Comment by jtarrio** [comment]
I've updated the README to document all of this.
