### ISSUE TITLE
Doesn't play after pressing the Play button

### ISSUE THREAD

**Issue by herbbetz** [jtarrio/radioreceiver#2]
Hello, I just downloaded your code to my Win10 and have the following error with 'npm run dist' (or watch or build): 

D:\downloads4all\radioreceiver-main\radioreceiver-main>npm run dist

> radioreceiver@0.0.1 dist
> node ./build.mjs --dist

node:internal/modules/esm/resolve:857
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base), null);
        ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'esbuild' imported from D:\downloads4all\radioreceiver-main\radioreceiver-main\build.mjs
    at packageResolve (node:internal/modules/esm/resolve:857:9)
    at moduleResolve (node:internal/modules/esm/resolve:926:18)
    at defaultResolve (node:internal/modules/esm/resolve:1056:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:654:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:603:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:586:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:242:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:135:49) {
  code: 'ERR_MODULE_NOT_FOUND'
}

Node.js v22.12.0

**Comment by herbbetz** [comment]
I also cannot get any waterfall diagram from https://radio.ea1iti.es/, despite that my RTL-SDR V4 Stick is connecting via USB to this sites javascript ... (no error on chrome browser console)

**Comment by jtarrio** [comment]
For the first item, have you run `npm install`? I'm not extremely familiar with the NPM ecosystem so I don't know what's appropriate to add to the instructions and what's assumed that you know.

For the second item, do you get sound? Can you see the grid with the frequency and decibel divisions?

Maybe your decibel range (in the bottom left) is set too high. This is what mine looks like.

<img width="398" alt="image" src="https://github.com/user-attachments/assets/61e13d05-c6f2-4c15-b4a3-36406a8c6020" />

Try moving the left slider all the way to the left — or write `-150` where mine says `-90 dB`. Then adjust both ends of the decibel range to a nice, comfortable position :-)

**Comment by herbbetz** [comment]
Yes, this did it, Tnx for fast reply, did not know about 'npm install'. Now I have the same problem locally as on https://radio.ea1iti.es/ . On pressing the controls playbutton No sound, V4stick connected, no waterfall, no console error ...
![screen2](https://github.com/user-attachments/assets/3ca9a673-4203-474d-b38c-9ea5d88afa24)

**Comment by jtarrio** [comment]
That's odd. I'm going to ask you to set a few breakpoints to see if the execution flow gets interrupted at some point. I don't know how familiar you are with the developer tools so I will be explaining with a little too much detail (and maybe someone will read this in the future and will want to try the same thing), so please bear with me.

Please reload Radio Receiver's to start with a blank slate and press F12 to bring up the developer tools. In the "sources" tab, select the "main.js" file on the left and press Control-F to search.

Type "onStart()" (without quotes), and this will bring you to a line that's followed by a "dispatchEvent" statement. Please set a breakpoint on that "dispatchEvent" by clicking on the left side of the line, where a hyphen is. You'll know you clicked the correct place because a blue arrow-like thing will appear.

Next, search for "radio.start" (no quotes) and place a breakpoint on that line.

Next, search for "rtlProvider.get" (again, no quotes) and place a breakpoint on that line.

Finally, search for "device === void" (you know about the quotes) and place a breakpoint.

Now, leaving the developer tools open, press the Play button. The Radio Receiver screen will darken and you'll see "Paused in debugger" at the top.

Look at the developer tools window; the "dispatchEvent" line will be highlighted.

Press F8; the "radio.start" line should be highlighted.

Press F8 again; the "rtlProvider.get" line should be highlighted.

Press F8; the "device === void" line should be highlighted. At this point, do me a favor and hover your mouse pointer over "device"; after a second or so, the word "undefined" should appear.

Then you press F8 for a final time and get an error message that mentions user gestures. That's normal because we've been interrupting the execution of the program.

At some point, my description of what should happen will be different from what you see, so please tell me how it went :-)

**Comment by herbbetz** [comment]
There is no difference from what you described either on http://127.0.0.1:5500/index.html (VSCode Live Server local release) nor on https://radio.ea1iti.es/. "device" is undefined at breakpoint #4 and after pressing F8 the "user gestures error" appears. Did not watch any values on the first 3 breakpoints though. If I connect the device before setting the last breakpoint, device is 'not available' and a skull appears instead of the control play arrow. I am running chrome 131.0.6778.205 (Official Build) (64-bit) as administrator on win10.
![screen4](https://github.com/user-attachments/assets/edb5ce57-20e8-4aac-a9af-1772954b903c)

**Comment by jtarrio** [comment]
Mm I had assumed you didn't even see the "connect to USB device" dialog, but I guess you do? I don't have much time to diagnose in the next couple of days but you look like you know your way around code, so you could check around the "getSamples" function in rtl8232u.ts and other rtl-related or radio.ts functions to see if it's failing silently at some point. Could be something as silly as forgetting to add an "await" in a function that interacts with USB...

I'll try to have another look when I can. And thanks for the report and your willingness to diagnose, those always help make the software better :-)

**Comment by herbbetz** [comment]
Thanks, yes, I see the connect dialog and the connect is working (see the trident USB symbol in the chrome tab of my 1st image), but then nothing happens... maybe more time to debug after Xmas... wish you Happy Xmas Holidays.

**Comment by herbbetz** [comment]
Ok, I got it to run by accident. On another PC I had installed the Airspy SDRsharp, when I bought the RTL-SDR V4 Stick in 2023. It comes with a utility called 'Zadig', which will install a special USB driver for the stick. 
![zadig](https://github.com/user-attachments/assets/872ed2bf-32a1-45bd-8ed7-68f9d7fe3474)
While I ran Zadig on my main PC (Win10), all suddenly started to work. Your index.html even works, when loaded in chrome as a file and also from VScode Liveserver or https://radio.ea1iti.es/. 
It did not run without the Zadig driver on another laptop running Win11.
(Did not get [this software](https://meshuga.github.io/web-spectrum/) to run though despite Zadig driver. )

**Comment by jtarrio** [comment]
It's interesting that, without Zadig, it fails silently instead of not showing the RTL in the dialog or showing an error message.

Anyway, I'm glad you got it to work! I'll see if I can reproduce this in my Windows machine and see if I can add some detection to guide people to the solution.

(The solution for those who come here in the future: use Zadig to install the WinUSB driver for the RTL stick.)

**Comment by herbbetz** [comment]
In Ubuntu Chrome I was not yet able to even get WebUSB permissions. 
![ubuntu-webUSB](https://github.com/user-attachments/assets/5793c954-5a70-4278-a05e-301838a8977b)
If somebody knows, how to do this, please give me a hint (my udev rule was of no success). If this could be resolved, would I need a special USB driver in a linux too (like Zadig's on Windows)? How is this in MacOS?
Sidenote: GnuRadio (on raspian bookworm/ RPi4B) also failed for me with my RTL-SDR-Stick V4, whereas V3 seems better supported.

**Comment by jtarrio** [comment]
I can only suggest the following:

```
echo 'blacklist dvb_usb_rtl28xxu' | sudo tee --append /etc/modprobe.d/blacklist-dvb_usb_rtl28xxu.conf
```

Followed by a reboot to make sure it takes.

**Comment by herbbetz** [comment]
Yes, you were right, I got 'https://radio.ea1iti.es/' to run on ubuntu 22.04 /chrome 131.0 by running all the linux commands proposed in https://www.rtl-sdr.com/v4/ , which includes your blacklist command too. Thanks
----Quote:
On Linux the procedure is also simple and just involves removing any existing RTL-SDR drivers, and installing our version.

Purge the previous driver:
  sudo apt purge ^librtlsdr
  sudo rm -rvf /usr/lib/librtlsdr* /usr/include/rtl-sdr* /usr/local/lib/librtlsdr* /usr/local/include/rtl-sdr* /usr/local/include/rtl_* /usr/local/bin/rtl_*
Install the RTL-SDR Blog drivers:
  sudo apt-get install libusb-1.0-0-dev git cmake pkg-config
  git clone https://github.com/rtlsdrblog/rtl-sdr-blog
  cd rtl-sdr-blog
  mkdir build
  cd build
  cmake ../ -DINSTALL_UDEV_RULES=ON
  make
  sudo make install
  sudo cp ../rtl-sdr.rules /etc/udev/rules.d/
  sudo ldconfig
Blacklist the DVB-T TV drivers:
  echo 'blacklist dvb_usb_rtl28xxu' | sudo tee --append /etc/modprobe.d/blacklist-dvb_usb_rtl28xxu.conf
Reboot


Works also on raspberry4B /bookworm with chromium 130.0 , but choppy sound when connected over VNC (despite LAN, not WLAN).
